### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by abscbnvote** [curtisshipley/CognitoForms#1]
I provided the user pool ID and client ID and tried to use the app. I tried to sign in using the username and password registered to our userpool but I get the error "Index was outside the bounds of the array. (IndexOutOfRangeException)" I am new to Xamarin forms and AWS and wanted to try out this simple sign in. Is there anything I need to change for it to work? Thank you!

**Comment by curtisshipley** [comment]
Can you past the stack trace here? That would be very helpful figuring out where the problem might be.

**Comment by abscbnvote** [comment]
I tried to but nothing is showing. I am running the app on Xamarin Live Player and the error only appears on the live player. nothing shows on visual studio.

**Comment by abscbnvote** [comment]
To add I think it says "Uncaught Exception"

**Comment by curtisshipley** [comment]
The Amazon libraries may not work on the Live Player, which that exception indicates. If you run it in an emulator or on a live device does it work?  

If you email me the pool id, client id and region, plus a user id & password, I will try it.

**Comment by abscbnvote** [comment]
Let me try it as well on an emulator.
Pool ID:  ap-southeast-1_QXqWhPGaK
Client ID: 4vmfhpckenlmepj9vs12kmfru7
Region: APSoutheast1
user: testaccount
password: Test_Account2018

**Comment by curtisshipley** [comment]
I tried with the user and password after changing the pool, client and region, but go an Cognito API response of user not found. 

I've pushed a change to master with a pool and client id that I created. You can test it with a userid of testit@saltydogtechnology.com and a password of Cognito_2018.

**Comment by curtisshipley** [comment]
Were you able to test it?

**Comment by abscbnvote** [comment]
Its working on the emulator finally! I was also able to use our own user pool ID. However I see that accounts are forced to change password. I did follow the password policy however it says that on the console that the password update failed.
![updatepasswordfailed](https://user-images.githubusercontent.com/40511944/41953610-37b96e74-7a09-11e8-858b-281e8166fd52.PNG)

**Comment by abscbnvote** [comment]
I am trying to re-create your app but I see some of the classes have a different namespace which is SaltyDog.CognitoForms. Why are their namespaces different?

**Comment by curtisshipley** [comment]
The name spaces were different because of an incomplete rename. I've pushed an update to master that makes them all SaltyDog.CognitoForms.*.

It will ask for a password change if the return from Amazon Cognito requests it. After you create a user in the cognito console, you will see its state is FORCE_CHANGE_PASSWORD. Currently, there is does not appear to be a way to change this directly in the console. However it can be done via the command line.

See this for more information:
https://stackoverflow.com/a/45253010/57114

I'm in the process of creating a new version of CognitoForms which will have a reusable library that can be installed via nuget, if that is of any interest.

**Comment by abscbnvote** [comment]
Thank you so much! We rarely see Xamarin Forms and AWS used together which made it hard to study. But this has been a great help. I'll go ahead and work on the CLI and will let you know if we need any further help. Will surely keep on checking this thread for your work in progress on the reusable library. Again, thank you!

**Comment by curtisshipley** [comment]
I'm glad you found it useful! 

I will go ahead and close this issue. You can open a new one, or contact me directly at the email in my github profile.
