### ISSUE TITLE
Guidance on using other AWS services with this

### ISSUE THREAD

**Issue by capps1994** [curtisshipley/CognitoForms#16]
I have been trying to figure out how to use other aws services with this class.

would it be possible to get some guidance please?

**Comment by curtisshipley** [comment]
What are you trying to do?

**Comment by capps1994** [comment]
Thanks for the quick reply. I would like to use s3 to upload to a bucket but the session keys don’t seem to work, I’m guessing I am missing something?

**Comment by capps1994** [comment]
I have got this working with the following
`var provider = new AmazonCognitoIdentityProviderClient(new AnonymousAWSCredentials(),Amazon.RegionEndpoint.EUWest1);
                    CognitoUserPool userPool = new CognitoUserPool("pool_id", "Client_id", provider);
                    CognitoUser user = new CognitoUser(Session.UserName, Client_id", userPool, provider);

                    string password = "password";

                    AuthFlowResponse context = await user.StartWithSrpAuthAsync(new InitiateSrpAuthRequest()
                    {
                        Password = password
                    }).ConfigureAwait(false);

                    CognitoAWSCredentials credentials =
                        user.GetCognitoAWSCredentials("eu-west-1:9d6bca5a-3b62-4c6d-8771-dffd4931417a", Amazon.RegionEndpoint.EUWest1);



                    using (var s3client = new AmazonS3Client(credentials, Amazon.RegionEndpoint.EUWest1))
                    {
                        try
                        {
                            using (TransferUtility fileTransferUtility = new TransferUtility(s3client))
                            {
                                await fileTransferUtility.UploadAsync(responseBody, "xamarintest", "petitionData");
                            }
                        }
                        catch (Exception exp)
                        {
                            System.Diagnostics.Debug.WriteLine(exp);
                        }
                       
                    }`

However what would be the best way to store/get the user as i can see that you do most of the code already in your Sign in method?

**Comment by curtisshipley** [comment]
The trick is getting the CognitoAWSCredentials so you can initialize the AmazonS3Client. There are a couple ways to do this: First, modify the SignOnContext to return the user, then use it when you need the CognitoAWSCredentials. The second option, recreate the CognitoUser from the tokens. There is a constructor that takes the tokens and an endpoint. Once re-created, in theory, you can get the CognitoAWSCredentials. I haven't specifically tried this, however.

You will have to configure user permissions Cognito settings to allow S3. Most examples use identity pools. You might be able to associate IAM roles with cognito user groups.

**Comment by capps1994** [comment]
I can see that returning the user was commented out 

```
public async Task<SignInContext> SignIn(string userName, string password)
		{
            try
            {

                var credentials = new AnonymousAWSCredentials();


                using (var client = new AmazonCognitoIdentityProviderClient(credentials, RegionEndpoint))
                {
                    CognitoUserPool userPool = new CognitoUserPool(PoolId, ClientId, client);
                    CognitoUser user = new CognitoUser(userName, ClientId, userPool, client);

                    AuthFlowResponse context = await user.StartWithSrpAuthAsync(new InitiateSrpAuthRequest()
                    {
                        Password = password
                    }).ConfigureAwait(false);

                    // TODO handle other challenges
                    if (context.ChallengeName == ChallengeNameType.NEW_PASSWORD_REQUIRED)
                        return new SignInContext(CognitoResult.PasswordChangeRequred)
                        {
                            //User = user,
                            SessionId = context.SessionID
                        };
                    else
                    {

                        return new SignInContext(CognitoResult.Ok)
                        {
                            //User = user,
                            IdToken = context.AuthenticationResult?.IdToken,
                            RefreshToken = context.AuthenticationResult?.RefreshToken,
                            AccessToken = context.AuthenticationResult?.AccessToken,
                            TokenIssued = user.SessionTokens.IssuedTime,
                            Expires = user.SessionTokens.ExpirationTime,
                            SessionId = context.SessionID

                        };
                    }
                }
            }
```

I have uncommeted these, but i can see that the signin view controller saves it the the data of that object to sessionStore class, Plugin.Settings.Abstractions; doesn't support storing whole objects.

is it worth storing this in a new class that I can access.?

**Comment by capps1994** [comment]
just writing to say that i have something working!

i created a new class that basicly holds the user
```
using System;
using Amazon.Extensions.CognitoAuthentication;

namespace SaltyDog.CognitoForms.Util
{
    public class AuthenicatedUser
    {
        public CognitoUser User { get; set; }
        private static AuthenicatedUser _instance = null;

        public AuthenicatedUser()
        {
        }

        public static AuthenicatedUser Instance()
        {
            if (_instance == null)
            {
                _instance = new AuthenicatedUser();
            }

            return _instance;
        }
    }
}
```

I also got the sign in method to make an instance of that class and pass the CognitoUser Object

**Comment by curtisshipley** [comment]
I'm glad to hear you have something working!!

If I were doing it, I probably would try to reconstitute the CognitoUser from the tokens. This is because there was an unspoken design goal of not having the app be aware of the implementation details below.  

But you're free to do what you would like.

**Comment by capps1994** [comment]
yeah im going to look at if i can recreate the user object from the tokens, i found one flaw, if you close the app the object is obviously gone :'(

**Comment by capps1994** [comment]
I cannot see how to get a Cognito user from the tokens :(

**Comment by curtisshipley** [comment]
I believe you have to do it something like this:

```
CognitoUser user = new CognitoUser("", ClientId, userPool, provider);
user.SessionTokens = new CognitoUserSession(idToken, accessToken, refreshToken, issued, expires);

```

And there might be an issue with the issue and/or expired values, and need to be set according to this:

https://github.com/aws/aws-sdk-net-extensions-cognito/issues/24#issuecomment-468913164

Where the expires value looks like it needs to be expiry of the refresh token, not the session token.

**Comment by capps1994** [comment]
this did work with the following code:
```
var provider = new AmazonCognitoIdentityProviderClient(new AnonymousAWSCredentials(), Amazon.RegionEndpoint.EUWest1);
                    CognitoUserPool userPool = new CognitoUserPool("pool_id", "client_id", provider);
                    CognitoUser user = new CognitoUser("", "client_id", userPool, provider);
                    user.SessionTokens = new CognitoUserSession(
                                                                session.IdToken,
                                                                session.AccessToken,
                                                                session.RefreshToken,
                                                                session.TokenIssuedServer,
                                                                DateTime.Now.AddHours(1));

                    var authresponse = await user.StartWithRefreshTokenAuthAsync(new InitiateRefreshTokenAuthRequest
                    {
                        AuthFlowType = AuthFlowType.REFRESH_TOKEN
                    });

                    CognitoAWSCredentials credentials =
                        user.GetCognitoAWSCredentials("identity_id", Amazon.RegionEndpoint.EUWest1);
```

**Comment by capps1994** [comment]
thanks for all your help.
 I have got this working with temp creds
