### ISSUE TITLE
Unable to Install Amazon.Extensions.CognitoAuthentication

### ISSUE THREAD

**Issue by hochmayrfa** [curtisshipley/CognitoForms#2]
Hello,

I'm Trying to follow your tutorial on [your tutorial](https://www.saltydogtechnology.com/xamarin-forms-aws-cognito/) but I can't install the Nugget package Amazon.Extensions.CognitoAuthentication. 

It seems that this package is not available for .NETPortable. 

I got the following error : 

Could not install package 'AWSSDK.Extensions.CognitoAuthentication 0.9.4'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

So is there a workaround for your tutorial ?

**Comment by curtisshipley** [comment]
So I think the issue is that Profile111 is .Net Standard 1.1/PCL, and AWSSDK.Extensions.CognitoAuthentication 0.9.4 only supports .Net Standard 1.3.  

What version of Xamarin Forms are you using? What version of Visual Studio are you using? What mobile platforms are you targeting ?

**Comment by hochmayrfa** [comment]
I guess it's impossible for me to use Cognito inside my Xamarin App then..


Microsoft Visual Studio Community 2017 
Version 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

ASP.NET and Web Tools 2017   15.0.40601.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40608.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.0.40608.0
Azure Functions and Web Jobs Tools

C# Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.19-rc (a4ffc1b)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

Telerik Xamarin VSExtensions   2018.2.710.1
Progress® Telerik® UI for Xamarin Visual Studio extensions

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 173513e369ffb7a1c4d5dccf83696d9aac2ab2d0.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27703.2035
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Xamarin   4.10.10.2 (35a01d8dc)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.1 (f3257e429)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by curtisshipley** [comment]
I would not draw that conclusion. 

The problem is that a **Profile111** project is PCL/.Net Standard 1.1, and not compatible with CognitoAuthentication. .Net Standard 1.3 or greater is required. (See the nuget page for CognitoAuthentication.)

To fix, try changing the .Net version for your app to .Net Standard 1.3, or convert it to a .Net Standard 2.0. 

This may be of interest: 

https://mallibone.com/post/migrate-from-pcl-to-net-standard

Please answer the other questions I asked, too:

- What operating systems is your Xamarin Forms app targeting? Android? IOS? or?
- What version of the Xamarin Forms library are you using? 2.5? 3.0? or ?

**Comment by hochmayrfa** [comment]
Your other question is already answered in my previous comment, I guess I edited it at the moment you were writing your answer. 

I'm targeting Android and iOS. 
Xamarin.Forms : v3.1.0.697729

I'm following your link to change my project into a .Net Standard project. I will come back to you after some testing.

Thank you really much for your help

**Comment by curtisshipley** [comment]
You're welcome. Let me know how it goes.

**Comment by hochmayrfa** [comment]
It works with .Net Standard ! 
Thank you, I hope thay will support the .Net Portable one day, Importing my project to .Net Standard will be hard ahah

**Comment by curtisshipley** [comment]
I'm glad it worked!
