### ISSUE TITLE
Bad Code when entering code sent from AWS

### ISSUE THREAD

**Issue by BryanGerre** [curtisshipley/CognitoForms#4]
Using the project I get a Bad Code when entering code sent from AWS. I've tried many emails and the confirmation code sent to email from cognito is recognized as "bad code the validation code was not correct". I'm imputing the code received in the email. If I manually add the user to a group and confirm in aws then I can log in as authenticated user

**Comment by curtisshipley** [comment]
I would suspect AWS setup, too. If, say, the keys were incorrect, then I wouldn't expect it to work at all.
The first place I'd look is the client settings in cognito setup. I would initially try it with 2 factor auth, and remember device off.

**Comment by curtisshipley** [comment]
@BryanGerre  Where you able to find a resolution?

**Comment by BryanGerre** [comment]
Not yet. I’m starting from scratch today. I’ll let you know asap if the issue is solved. I’m going off of your website for the directions. Thanks for checking

 

Bryan Gerrells

Information Systems

Direct Systems Inc

804-320-2040 Ext. 103

 <http://www.directsystems.com/> http://www.directsystems.com/

 

 <http://www.directsystems.com/>

**Comment by curtisshipley** [comment]
Thanks. Let me know if there is anything I need to update in the post.

**Comment by BryanGerre** [comment]
Yes. In the apiconfig.cs the region endpoints need to be set for your region.

**Comment by BryanGerre** [comment]
I meant the ApiCognito.cs

**Comment by stownend** [comment]
Thanks @BryanGerre , that was the problem. There were several hardcoded regions in ApiCognito.cs, changing them all to use the RegionEndpoint property did the trick.

**Comment by curtisshipley** [comment]
Closing. I've merged a pull request that updates the RegionEndpoints
