### ISSUE TITLE
Not saving dateTimes properly

### ISSUE THREAD

**Issue by RidhwanDev** [curtisshipley/CognitoForms#6]
When using the SessionStore in SignInViewModel.cs, it seems that the lines ```SessionStore.TokenIssuedServer = result.TokenIssued;```
```SessionStore.TokenExpiresServer = result.Expires;``` 
are not correctly storing these times into the session store and as a result of this 
```Session.IsLoggedIn(DateTime.Now)```
 always fails.

Have I messed something up here? or can you also confirm this is the current behaviour.

**Comment by RidhwanDev** [comment]
Just realised its not actually about the saving, its saving it just fine... just seems to not be serialising the DateTime object properly. Setting it to an hour behind. I'm currently in British Summer Time which i s+0100 at the moment, could this be messing with it?

**Comment by RidhwanDev** [comment]
This problem is with the Xamarin settings library sorry. Closing.

**Comment by curtisshipley** [comment]
I'm glad you found it, and thanks for the heads up.

**Comment by RidhwanDev** [comment]
Hey man, 
Just wanted to let you know what I found out and how I fixed it, James Montemagno states [here](https://github.com/jamesmontemagno/SettingsPlugin/issues/29) that "Date times are always stored in UTC. This is as designed.". After looking at his [source code](https://github.com/jamesmontemagno/SettingsPlugin/blob/master/src/Plugin.Settings/Settings.dotnet.cs) I found that he uses `.ToUniversalTime()` on every DateTime object used. So in order for this took work with your code based, I changed ` if (Session.IsLoggedIn(DateTime.Now))` in App.xaml.cs to `if (Session.IsLoggedIn(DateTime.Now.ToUniversalTime()))`. Checks the DateTime appropriately now and will skip past sign in page as intended. Just having some weird issue at the moment with what I think is after an hour? Maybe when the token has expired,not to sure at the moment but when I do the first build after like an hour or so of using same token I get some xaml error which stems from `await OnAuthenticated();` in SignInViewModel.cs.  Will try to figure out what is going on. Nethertheless, great job with this library man, It really helped save a LOT of time setting up cognito. Thank you.

**Comment by RidhwanDev** [comment]
`    Device.BeginInvokeOnMainThread(() =>`
    `        {`
                `MainPage = new MainPage(Session);`
         `   });`
Works fine when being called via `Unauthenticated();` but doesn't like the 'Device.BeginInvokeOnMainThread` when its being called directly in the App.xaml.cs. This might just be an iOS thing (not really testing android at the moment). So, I've changed InitializeMainPage to this. Error is gone.

` public async void InitializeMainPage()`
      `  {`
           ` if (Session.IsLoggedIn(DateTime.Now.ToUniversalTime()))`
                `MainPage = new MainPage(Session);`
           ` else`
               ` Unauthenticated();`
     `   }`

**Comment by curtisshipley** [comment]
Thanks @RidhwanDev  If you want to throw that into a PR, that would be great. I can merge it in!

**Comment by RidhwanDev** [comment]
Sure, I'll do that tonight.
