### ISSUE TITLE
While Email based registration is successful, Signin is not working. 

### ISSUE THREAD

**Issue by cjkarande** [curtisshipley/CognitoForms#9]
While Email based user registration is successful, SignIn is not working. 

ApiCognito->SignIn->AuthFlowResponse context = await user.StartWithSrpAuthAsyn... waits indefinitely without any error value.

**Comment by curtisshipley** [comment]
Make sure the regions are set correctly in ApiRegion.EndPoint so they match the region where you created the pool.  Let me know if that works.

**Comment by cjkarande** [comment]
Thanks for your reply. I am encountering this issue with the Sample app itself within this repository.

I Just replaced the PoolId, ClientId & Region Endpoint with my relevant data.
 Interestingly the registration & verification is working absolutely fine. However the signin Api gets blocked blocked with no return value or exception as mentioned previously

**Comment by o2x7** [comment]
Addressed in my PR: https://github.com/curtisshipley/CognitoForms/pull/12 I submitted today

**Comment by cjkarande** [comment]
> Could it be this issue?
> #3

Yes we can actually close this issue
